sudo: required
dist: trusty
install: git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
before_script:
 - export GNUPGHOME=~/qubes-builder/keyrings/git
 - mkdir --parents "$GNUPGHOME"
 - chmod --recursive 700 "$GNUPGHOME"
 - gpg --import ~/qubes-builder/qubes-developers-keys.asc
 - echo '427F11FD0FAA4B080123F01CDDFA1A3E36879494:6:' | gpg --import-ownertrust
 - gpg --keyserver keys.gnupg.net --recv-keys "916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA"
 - gpg --fingerprint "916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA"
 - echo '916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA:6:' | gpg --import-ownertrust
 - gpg --fingerprint "916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA"
 - export VERBOSE=3
 - export DEBUG=1
#- export REPO_PROXY=http://127.0.0.1:3142
 - export CHECK_BRANCH=1
 - export BRANCH_template_whonix=master
 - export GIT_URL_template_whonix=https://github.com/adrelanos/qubes-template-whonix.git
 - export BUILDER_PLUGINS="template-whonix builder-debian"
 - env
script: ~/qubes-builder/scripts/travis-build linux-template-builder
after_success:
 - ls -l ~/qubes-builder/qubes-src/linux-template-builder/rpm/noarch
language: generic
env:
# - DISTS_VM=whonix-gateway USE_QUBES_REPO_VERSION=3.1
# - DISTS_VM=whonix-workstation USE_QUBES_REPO_VERSION=3.1
 - DISTS_VM=whonix-gateway USE_QUBES_REPO_VERSION=3.1 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=whonix-workstation USE_QUBES_REPO_VERSION=3.1 USE_QUBES_REPO_TESTING=1
# - DISTS_VM=whonix-gateway USE_QUBES_REPO_VERSION=3.2
# - DISTS_VM=whonix-workstation USE_QUBES_REPO_VERSION=3.2
 - DISTS_VM=whonix-gateway USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=whonix-workstation USE_QUBES_REPO_VERSION=3.2 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=whonix-gateway USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
 - DISTS_VM=whonix-workstation USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
